### ISSUE TITLE
number of frames different than expected

### ISSUE THREAD

**Issue by jaderxnet** [dmoltisanti/brace#2]
Very cool the work,

I used youtube-dl to download YouTube videos. I downloaded RS0mFARO1x4 and used ffmpeg to extract the frames. But, I recovered 5368 frames, not 6517 frames as indicated in the RS0mFARO1x4_6382-6517_powermove.json.json file.

What did I do wrong?

Thanks,

**Comment by dmoltisanti** [comment]
Hey, thanks for your interest in BRACE!

Did you check [these instructions ](https://github.com/dmoltisanti/brace#videos-and-frames) to extract frames? In particular, we used the following settings for `youtube-dl` command:

```bash
format: bestvideo[ext=mp4],bestaudio[ext=m4a]
```

and this is how we extracted frames with ffmpeg:

```bash
ffmpeg -i ./path_to_videos/${video_id}.mp4 ./path_to_frames/${video_id}/img-%06d.png
```

Please let me know if this solves the issue!

**Comment by jaderxnet** [comment]
Thank you, I tested exactly these parameters and got the result 7859 PNGs

I have made my code accessible in this colab below. Am I doing something wrong? How do I synchronize frames with Brace annotations?

https://colab.research.google.com/drive/126631IE9aeGx_5S3jkFk-_yvjykHO95d?usp=sharing

**Comment by dmoltisanti** [comment]
Hi,

I had a look at your code and I can't see anything wrong. 

It seems though that now you get 7859 frames, so the issue should be solved since the segment `RS0mFARO1x4_6382-6517_powermove.json` is fully contained in your frames, right?

**Comment by jaderxnet** [comment]
Good. 

It means that these segments do not cover the whole video, right? I will test the sync now. Thanks.

**Comment by dmoltisanti** [comment]
That is correct. The original videos are  very long and segments only  cover a small part. 

I will close this issue now, but feel free to reopen it if you still face issues!
