### ISSUE TITLE
Raw Audio Files

### ISSUE THREAD

**Issue by mucunzhuzhu** [dmoltisanti/brace#4]
I'm very interested in your work, can you provide the raw audio files please?

**Comment by dmoltisanti** [comment]
Hi, thanks for your interest! Unfortunately we can't release audio or video files due to copyright, but it's easy to extract the audio from the YouTube videos. You can also have a look at the [pre-extracted audio features](https://github.com/dmoltisanti/brace/releases/tag/af_v1.0)
